/* eslint-disable @next/next/no-html-link-for-pages, @next/next/no-location-assign-relative-destination, react-hooks/set-state-in-effect */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import {
  AlertTriangle, ArrowRight, Bell, CheckCircle2, Database,
  Download, FileText, Globe2, Heart, Languages, LogOut, MapPin, Menu, Moon,
  Radio, RefreshCw, Search, Send, ShieldCheck, Sun, Trash2, Video, Waves, Wifi, X
} from "lucide-react";
import { Switch } from "@/components/ui/switch";
import { TubesBackground } from "@/components/ui/neon-flow";
import RealWaterMap,{waterStations,type StationStatus,type WaterStation} from "@/components/real-water-map";
import {t,type Language} from "@/lib/riverpulse-i18n";

const routes=[
  ["nav.home","/"],["nav.map","/map"],["nav.water","/water/esil"],["nav.robots","/robots/rc-01"],
  ["nav.analytics","/analytics"],["nav.reports","/reports"],["nav.learn","/learn"],["nav.about","/about"],
] as const;
const statusClass:Record<StationStatus,string>={normal:"ok",attention:"warn",risk:"danger",offline:"muted-status"};
const statusKey:Record<StationStatus,string>={normal:"common.normal",attention:"common.attention",risk:"common.risk",offline:"common.offline"};
const loc=(language:Language,ru:string,kz:string,en:string)=>language==="RU"?ru:language==="KZ"?kz:en;
const noop=()=>{};

function Brand(){return <a className="rp-brand" href="/"><span><Waves size={22}/></span>RiverPulse</a>}
function Header({language,setLanguage,theme,setTheme}:{language:Language;setLanguage:(x:Language)=>void;theme:string;setTheme:(x:string)=>void}){
  const [menu,setMenu]=useState(false);const path=typeof window!=="undefined"?window.location.pathname:"/";
  return <header className="rp-header"><div className="rp-header-main shell"><Brand/><div className="rp-header-actions">
    <button className="rp-icon-button" aria-label="Change language" onClick={()=>setLanguage(language==="RU"?"KZ":language==="KZ"?"EN":"RU")}><Languages size={18}/><b>{language}</b></button>
    <button className="rp-icon-button" aria-label="Theme" onClick={()=>setTheme(theme==="dark"?"light":"dark")}>{theme==="dark"?<Sun size={18}/>:<Moon size={18}/>}</button>
    <a className="rp-button secondary desktop-action" href="/login">{t(language,"nav.signin")}</a><a className="rp-button primary desktop-action" href="/map">{t(language,"nav.openMap")}</a>
    <button className="rp-icon-button mobile-menu" aria-label={t(language,"nav.menu")} aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={19}/>:<Menu size={19}/>}</button>
  </div></div><nav className={"rp-tabs "+(menu?"open":"")} aria-label={t(language,"nav.menu")}><div className="shell rp-tabs-inner">{routes.map(([key,href])=><a key={href} className={path===href||(href!=="/"&&path.startsWith(href+"/"))?"active":""} href={href}>{t(language,key)}</a>)}<a className="mobile-nav-login" href="/login">{t(language,"nav.signin")}</a></div></nav></header>
}
function DemoNotice({language}:{language:Language}){return <div className="rp-demo"><AlertTriangle size={16}/>{t(language,"common.demoWarning")}</div>}
function Badge({status,language}:{status:StationStatus;language:Language}){return <span className={"rp-badge "+statusClass[status]}>{t(language,statusKey[status])}</span>}
function Metric({label,value,meta}:{label:string;value:string;meta?:string}){return <article className="rp-card rp-metric"><span>{label}</span><strong>{value}</strong>{meta&&<small>{meta}</small>}</article>}
function Sparkline({values=[8,11,9,14,12,17,13,18]}:{values?:number[]}){const max=Math.max(...values);const pts=values.map((v,i)=>((i/(values.length-1))*100)+","+(34-(v/max)*28)).join(" ");return <div className="rp-spark-wrap"><svg className="rp-spark" viewBox="0 0 100 36" preserveAspectRatio="none"><polyline points={pts} fill="none" stroke="#22c55e" strokeWidth="2"/></svg><div className="rp-spark-axes"><small>X: время</small><small>Y: значение</small></div></div>}
function LineChart({values,x="Время",y="Значение"}:{values:number[];x?:string;y?:string}){const max=Math.max(...values);const min=Math.min(...values);const pts=values.map((v,i)=>((i/(values.length-1))*100)+","+(92-(v/max)*72)).join(" ");return <div className="rp-axis-chart"><span className="rp-axis-y">{y}</span><div className="rp-axis-ticks"><small>{max}</small><small>{Math.round((max+min)/2)}</small><small>{min}</small></div><div className="rp-axis-plot"><div className="rp-line-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={"0,100 "+pts+" 100,100"} fill="#22c55e18"/><polyline points={pts} fill="none" stroke="#22c55e" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg></div><div className="rp-axis-xticks"><small>1</small><small>{Math.ceil(values.length/2)}</small><small>{values.length}</small></div><span className="rp-axis-x">{x}</span></div></div>}
function PageTitle({kicker,title,subtitle,action}:{kicker?:string;title:string;subtitle?:string;action?:React.ReactNode}){return <div className="rp-page-title"><div>{kicker&&<span className="rp-kicker">{kicker}</span>}<h1>{title}</h1>{subtitle&&<p>{subtitle}</p>}</div>{action}</div>}

function Home({language}:{language:Language}){
  const [selected,setSelected]=useState(waterStations[0]);const choose=useCallback((s:WaterStation)=>setSelected(s),[]);
  const steps=[["home.measure","home.measureText"],["home.analyze","home.analyzeText"],["home.respond","home.respondText"],["home.result","home.resultText"]];
  return <><main><TubesBackground className="rp-welcome-flow"><section className="rp-welcome shell"><div className="rp-welcome-copy"><span className="rp-kicker">{t(language,"home.kicker")}</span><h1>{t(language,"welcome.title")}</h1><p>{t(language,"welcome.description")}</p><div className="rp-actions"><a className="rp-button primary" href="/register">{t(language,"welcome.register")}<ArrowRight size={17}/></a><a className="rp-button secondary" href="/map">{t(language,"home.explore")}</a></div><div className="rp-welcome-tags"><span>{t(language,"home.monitoring")}</span><span>{t(language,"home.ai")}</span><span>{t(language,"home.cleanup")}</span></div></div></section></TubesBackground>
  <section className="rp-welcome-preview shell"><div><span className="rp-kicker">{t(language,"welcome.preview")}</span><h2>{t(language,"home.title")}</h2><p>{t(language,"home.subtitle")}</p><a href="/map" className="rp-button secondary">{t(language,"nav.openMap")}<ArrowRight size={16}/></a></div><div className="rp-welcome-map"><RealWaterMap language={language} selectedId={selected.id} onSelect={choose}/></div></section>
  <section id="platform" className="rp-section shell"><PageTitle kicker={loc(language,"01 — Процесс","01 — Жұмыс тәртібі","01 — Workflow")} title={t(language,"home.workflow")}/><div className="rp-step-grid">{steps.map(([a,b],i)=><article className="rp-card rp-step" key={a}><span>0{i+1}</span><h3>{t(language,a)}</h3><p>{t(language,b)}</p></article>)}</div></section>
  <section className="rp-section shell"><PageTitle kicker={loc(language,"02 — Текущая сводка","02 — Ағымдағы шолу","02 — Live overview")} title={t(language,"home.dashboard")}/><DemoNotice language={language}/><div className="rp-dashboard-preview"><div className="rp-metric-grid"><Metric label={t(language,"analytics.stations")} value="6"/><Metric label={t(language,"analytics.online")} value="83%"/><Metric label={t(language,"analytics.alerts")} value="3"/><Metric label={t(language,"analytics.collected")} value="186 kg"/></div><div className="rp-dashboard-split"><div className="rp-card rp-panel"><h3>{loc(language,"Состояние воды","Судың күйі","Water Condition")}</h3><LineChart values={[70,72,68,75,77,73,79,81,78,82]} x={loc(language,"Время, дни","Уақыт, күн","Time, days")} y={loc(language,"Индекс, %","Индекс, %","Index, %")}/></div><AlertFeed language={language} compact/></div></div></section>
  <section className="rp-cta shell"><div><h2>{t(language,"home.cta")}</h2><p>{t(language,"home.ctaText")}</p></div><a className="rp-button primary" href="/map">{t(language,"nav.openMap")}</a></section></main><Footer language={language}/></>
}

function MapPage({language}:{language:Language}){
  const [status,setStatus]=useState<StationStatus|"all">("all");const [query,setQuery]=useState("");const [selected,setSelected]=useState(waterStations[0]);const choose=useCallback((s:WaterStation)=>setSelected(s),[]);
  const filtered=useMemo(()=>waterStations.filter(s=>(status==="all"||s.status===status)&&(s.name[language]+" "+s.waterBody[language]).toLowerCase().includes(query.toLowerCase())),[status,query,language]);
  const shown=filtered.find(s=>s.id===selected.id)||filtered[0];
  return <main className="rp-map-page"><div className="rp-map-toolbar"><div><h1>{t(language,"map.title")}</h1><p>{t(language,"map.subtitle")}</p></div><DemoNotice language={language}/></div><div className="rp-map-layout"><aside className="rp-card rp-map-filters"><label className="rp-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t(language,"map.search")}/></label><h3>{t(language,"map.layers")}</h3>{(["all","normal","attention","risk","offline"] as const).map(item=><button className={status===item?"active":""} key={item} onClick={()=>setStatus(item)}>{item==="all"?t(language,"map.all"):t(language,statusKey[item])}<span>{item==="all"?waterStations.length:waterStations.filter(s=>s.status===item).length}</span></button>)}</aside><RealWaterMap className="rp-main-map" language={language} stations={filtered} selectedId={shown?.id} onSelect={choose}/>{shown?<StationPanel station={shown} language={language}/>:<aside className="rp-card rp-station-panel">{t(language,"map.empty")}</aside>}</div></main>
}
function StationPanel({station,language}:{station:WaterStation;language:Language}){return <aside className="rp-card rp-station-panel"><Badge status={station.status} language={language}/><h2>{station.waterBody[language]}</h2><p>{station.name[language]}</p><div className="rp-coordinates"><MapPin size={15}/>{station.coordinates[1].toFixed(4)}, {station.coordinates[0].toFixed(4)}</div><div className="rp-detail-grid"><span>{t(language,"map.temperature")}<b>{station.temperature} °C</b></span><span>pH<b>{station.ph}</b></span><span>{t(language,"map.turbidity")}<b>{station.turbidity} NTU</b></span><span>{t(language,"map.oxygen")}<b>{station.oxygen} mg/L</b></span><span>{t(language,"map.conductivity")}<b>{station.conductivity} µS/cm</b></span><span>{t(language,"common.demo")}<b>{station.updated[language]}</b></span></div><a className="rp-button primary full" href={"/water/"+station.id}>{t(language,"common.details")}</a></aside>}

function WaterPage({language,station}:{language:Language;station:WaterStation}){
  const [period,setPeriod]=useState("24h");const [favorite,setFavorite]=useState(false);const [notify,setNotify]=useState(false);const [live,setLive]=useState(station.turbidity);
  useEffect(()=>{const id=setInterval(()=>setLive(v=>+(v+(Math.random()-.5)*.25).toFixed(1)),7000);return()=>clearInterval(id)},[]);
  const metrics=[[t(language,"map.temperature"),station.temperature+" °C"],["pH",String(station.ph)],[t(language,"map.turbidity"),live+" NTU"],[t(language,"map.oxygen"),station.oxygen+" mg/L"],[t(language,"map.conductivity"),station.conductivity+" µS/cm"],[loc(language,"Уровень воды","Су деңгейі","Water level"),"2.42 m"]];
  const chart:Record<string,number[]>={"24h":[6,7,6,8,9,11,8,10,12,9],"7d":[7,8,9,12,11,8,10],"30d":[8,7,10,11,14,12,9,8],"1y":[6,8,12,15,13,9,7]};
  return <main className="rp-content"><PageTitle kicker={station.name[language]+" · "+station.id.toUpperCase()} title={station.waterBody[language]} subtitle={station.updated[language]+" · "+t(language,"common.demo")} action={<div className="rp-actions compact"><button className={"rp-button secondary "+(favorite?"selected":"")} onClick={()=>setFavorite(!favorite)}><Heart size={17}/>{t(language,favorite?"water.favoriteOn":"water.favorite")}</button><button className={"rp-button secondary "+(notify?"selected":"")} onClick={()=>setNotify(!notify)}><Bell size={17}/>{t(language,notify?"water.notifyOn":"water.notify")}</button></div>}/><DemoNotice language={language}/><div className="rp-six-grid">{metrics.map(([a,b],i)=><article className="rp-card rp-water-metric" key={a}><span>{a}</span><strong>{b}</strong><Sparkline values={[8+i,11,9+i,14,12+i,17,13+i,18]}/><small><Radio size={12}/> {station.status==="offline"?t(language,"common.offline"):loc(language,"Датчик работает","Датчик жұмыс істейді","Sensor online")} · {t(language,"common.demo")}</small></article>)}</div><div className="rp-two-grid"><section className="rp-card rp-panel"><div className="rp-panel-head"><div><h2>{t(language,"water.period")}</h2><p>{t(language,"map.turbidity")} · NTU</p></div><div className="rp-periods">{["24h","7d","30d","1y"].map(x=><button key={x} className={period===x?"active":""} onClick={()=>setPeriod(x)}>{x}</button>)}</div></div><LineChart values={chart[period]} x={loc(language,"Время, ","Уақыт, ","Time, ")+period} y={loc(language,"Мутность, NTU","Лайлылық, NTU","Turbidity, NTU")}/></section><section className="rp-card rp-panel rp-ai"><span className="rp-kicker">RiverPulse AI</span><h2>{t(language,"water.aiTitle")}</h2><p>{t(language,"water.ai"+station.status[0].toUpperCase()+station.status.slice(1))}</p><div className="rp-inline-badges"><Badge status={station.status} language={language}/><span className="rp-badge ok">82% · {t(language,"common.demo")}</span></div><div className="rp-callout">{t(language,"water.aiWarning")}</div></section></div><section className="rp-card rp-panel rp-safety"><ShieldCheck size={25}/><div><h2>{t(language,"water.safety")}</h2><p>{t(language,"water.safetyText")}</p></div></section></main>
}

function RobotPage({language}:{language:Language}){
  const [overlay,setOverlay]=useState(false);
  const [compare,setCompare]=useState(50);
  const [cameraOn,setCameraOn]=useState(false);
  const [device,setDevice]=useState("");
  const [permissionMessage,setPermissionMessage]=useState("");
  const feed=useRef<HTMLElement>(null);
  const video=useRef<HTMLVideoElement>(null);
  const stream=useRef<MediaStream|null>(null);
  useEffect(()=>()=>{stream.current?.getTracks().forEach(track=>track.stop())},[]);

  async function enableCamera(){
    try{
      if(!navigator.mediaDevices?.getUserMedia)throw new Error("unsupported");
      stream.current=await navigator.mediaDevices.getUserMedia({video:true,audio:false});
      if(video.current){video.current.srcObject=stream.current;await video.current.play()}
      setCameraOn(true);setPermissionMessage(t(language,"robot.cameraNote"));
    }catch{stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;setPermissionMessage(t(language,"robot.permissionDenied"))}
  }
  function stopCamera(){stream.current?.getTracks().forEach(track=>track.stop());stream.current=null;if(video.current)video.current.srcObject=null;setCameraOn(false)}
  async function chooseBluetooth(){
    const bluetooth=(navigator as Navigator&{bluetooth?:{requestDevice:(options:{acceptAllDevices:boolean})=>Promise<{name?:string}>}}).bluetooth;
    if(!bluetooth){setPermissionMessage(t(language,"robot.bluetoothUnsupported"));return}
    try{const selected=await bluetooth.requestDevice({acceptAllDevices:true});setDevice(selected.name||"Bluetooth");setPermissionMessage("")}
    catch{setPermissionMessage(t(language,"robot.permissionDenied"))}
  }
  return <main className="rp-content"><PageTitle kicker="RC-01 · ES-CENTRAL-14" title={t(language,"robot.title")} subtitle={t(language,"common.demo")} action={<span className="rp-badge ok">{loc(language,"Симуляция очистки","Тазалау симуляциясы","Cleanup simulation")}</span>}/><DemoNotice language={language}/>
    <div className="rp-robot-permissions rp-card">
      <div><h2>{loc(language,"Доступ к устройствам","Құрылғыларға рұқсат","Device access")}</h2><p>{t(language,"robot.cameraNote")}</p></div>
      <div className="rp-robot-permission-actions"><button className="rp-button secondary" onClick={cameraOn?stopCamera:enableCamera}><Video size={17}/>{t(language,cameraOn?"robot.stopCamera":"robot.camera")}</button><button className="rp-button secondary" onClick={chooseBluetooth}><Wifi size={17}/>{device||t(language,"robot.bluetooth")}</button></div>
      {permissionMessage&&<p className="rp-permission-message" role="status">{permissionMessage}</p>}
    </div>
    <div className="rp-robot-grid"><section className="rp-live-feed" ref={feed}><video ref={video} className={cameraOn?"rp-device-video":"rp-device-video hidden"} autoPlay muted playsInline/>{!cameraOn&&<div className="rp-water-texture"/>}{overlay&&!cameraOn&&<><div className="rp-detection d1">{loc(language,"Бутылка","Бөтелке","Bottle")} · 91%</div><div className="rp-detection d2">{loc(language,"Банка","Қалбыр","Can")} · 84%</div></>}<div className="rp-feed-top"><span className="rp-live">{cameraOn?t(language,"robot.camera"):t(language,"common.demo")}</span><button aria-label={loc(language,"На весь экран","Толық экран","Fullscreen")} onClick={()=>feed.current?.requestFullscreen()}>⛶</button></div><div className="rp-feed-bottom"><Wifi size={15}/>{cameraOn?t(language,"robot.cameraNote"):loc(language,"Демо-видео робота недоступно","Роботтың демо-бейнесі қолжетімсіз","Robot demo video unavailable")}</div></section>
      <aside className="rp-card rp-panel"><h2>{t(language,"robot.status")}</h2>{[[t(language,"robot.battery"),"76%"],[t(language,"robot.speed"),"1.8 km/h"],["GPS","±1.4 m"],[t(language,"robot.container"),"43%"],[t(language,"map.temperature"),"48 °C"],[t(language,"robot.signal"),loc(language,"Хорошее","Жақсы","Good")]].map(([a,b])=><div className="rp-row" key={a}><span>{a}</span><b>{b}</b></div>)}<label className="rp-switch"><Switch checked={overlay} onCheckedChange={setOverlay}/>{t(language,"robot.overlay")}</label></aside></div>
    <div className="rp-two-grid"><section className="rp-card rp-panel"><h2>{t(language,"robot.route")}</h2><RealWaterMap language={language} stations={waterStations.slice(0,4)} selectedId="esil-central" onSelect={noop} className="rp-route-map"/></section><section className="rp-card rp-panel"><h2>{t(language,"robot.beforeAfter")}</h2><div className="rp-comparison" style={{background:"linear-gradient(100deg,#64748b 0 "+compare+"%,#0e7490 "+compare+"% 100%)"}}><span>{loc(language,"ДО","ДЕЙІН","BEFORE")}</span><span>{loc(language,"ПОСЛЕ","КЕЙІН","AFTER")}</span><i style={{left:compare+"%"}}>↔</i><input aria-label={loc(language,"Сравнение до и после","Дейін және кейін салыстыру","Before and after comparison")} type="range" min="8" max="92" value={compare} onChange={e=>setCompare(Number(e.target.value))}/></div></section></div>
  </main>
}

function AnalyticsPage({language}:{language:Language}){
  const labels=[[t(language,"analytics.stations"),"6"],[t(language,"analytics.online"),"83%"],[t(language,"analytics.alerts"),"3"],[t(language,"analytics.response"),"42 min"],[t(language,"analytics.collected"),"186 kg"],[t(language,"analytics.operations"),"14"]];
  return <main className="rp-content"><PageTitle kicker={loc(language,"Аналитика RiverPulse","RiverPulse аналитикасы","RiverPulse Intelligence")} title={t(language,"analytics.title")} subtitle={t(language,"analytics.subtitle")} action={<div className="rp-actions compact"><button className="rp-button secondary" onClick={()=>downloadCSV()}><Download size={16}/>CSV</button><button className="rp-button secondary" onClick={()=>window.print()}><FileText size={16}/>PDF</button></div>}/><DemoNotice language={language}/><div className="rp-six-grid analytics">{labels.map(x=><Metric key={x[0]} label={x[0]} value={x[1]}/>)}</div><div className="rp-two-grid"><section className="rp-card rp-panel"><h2>{loc(language,"Индекс состояния воды","Су күйінің индексі","Water Condition Index")}</h2><LineChart values={[72,74,70,69,76,78,75,79,81,80,83]} x={loc(language,"Время, недели","Уақыт, апта","Time, weeks")} y={loc(language,"Индекс, %","Индекс, %","Index, %")}/></section><section className="rp-card rp-panel"><h2>{loc(language,"Состав отходов","Қалдықтардың құрамы","Waste composition")}</h2><div className="rp-donut"/><p className="center">{loc(language,"Пластик 39% · Пакеты 25% · Банки 17% · Другое 19%","Пластик 39% · Пакеттер 25% · Қалбырлар 17% · Басқа 19%","Plastic 39% · Bags 25% · Cans 17% · Other 19%")}</p></section></div><section className="rp-card rp-panel"><h2>{t(language,"analytics.events")}</h2><RiverTable language={language}/></section></main>
}
function RiverTable({language}:{language:Language}){const rows=language==="RU"?[["Есиль · Центр","74 / 100","1","1 248","38 мин","92%"],["Нура · створ","63 / 100","2","986","51 мин","84%"],["Озеро Коргалжын","81 / 100","0","1 104","—","89%"]]:language==="KZ"?[["Есіл · Орталық","74 / 100","1","1 248","38 мин","92%"],["Нұра · тұстама","63 / 100","2","986","51 мин","84%"],["Қорғалжын көлі","81 / 100","0","1 104","—","89%"]]:[["Esil · Central","74 / 100","1","1 248","38 min","92%"],["Nura · Control","63 / 100","2","986","51 min","84%"],["Korgalzhyn Lake","81 / 100","0","1 104","—","89%"]];return <div className="rp-table-wrap"><table><thead><tr><th>{t(language,"nav.water")}</th><th>{loc(language,"Состояние воды","Судың күйі","Water Condition")}</th><th>{t(language,"analytics.alerts")}</th><th>{loc(language,"Измерения","Өлшемдер","Measurements")}</th><th>{t(language,"analytics.response")}</th><th>{loc(language,"Полнота","Толықтық","Completeness")}</th></tr></thead><tbody>{rows.map(row=><tr key={row[0]}>{row.map(cell=><td key={cell}>{cell}</td>)}</tr>)}</tbody></table></div>}
function downloadCSV(){const blob=new Blob(["water_body,status,alerts,measurements\nEsil,74,1,1248\nNura,63,2,986"],{type:"text/csv"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="riverpulse-report.csv";a.click();URL.revokeObjectURL(a.href)}

type DemoReport={id:string;category:string;date:string;description:string;location:string};
const demoReportsKey="riverpulse-demo-reports";
function ReportsPage({language}:{language:Language}){
  const [sent,setSent]=useState("");const [error,setError]=useState("");
  function submit(e:React.FormEvent<HTMLFormElement>){
    e.preventDefault();const form=new FormData(e.currentTarget);
    const description=String(form.get("description")||"").trim();
    if(description.length<15){setError(loc(language,"Введите не менее 15 символов.","Кемінде 15 таңба енгізіңіз.","Enter at least 15 characters."));return}
    const report:DemoReport={id:"RP-"+Date.now().toString().slice(-8),category:String(form.get("category")||""),date:String(form.get("date")||""),description,location:String(form.get("location")||"")};
    try{const saved=JSON.parse(localStorage.getItem(demoReportsKey)||"[]") as DemoReport[];localStorage.setItem(demoReportsKey,JSON.stringify([report,...saved].slice(0,20)));setSent(report.id)}
    catch{setError(loc(language,"Не удалось сохранить демо-обращение.","Демо өтінішті сақтау мүмкін болмады.","Could not save the demo report."))}
  }
  return <main className="rp-content"><PageTitle kicker={loc(language,"Обращения жителей","Тұрғындардың өтініштері","Citizen reports")} title={t(language,"reports.title")} subtitle={t(language,"reports.subtitle")}/><DemoNotice language={language}/><div className="rp-report-grid"><section className="rp-card rp-panel">{sent?<div className="rp-success"><CheckCircle2 size={32}/><h2>{t(language,"reports.success")}</h2><p>{sent} · {t(language,"reports.localOnly")}</p><button className="rp-button secondary" onClick={()=>setSent("")}>{t(language,"reports.another")}</button></div>:<form className="rp-form" onSubmit={submit}><label>{t(language,"reports.category")}<select name="category"><option>{loc(language,"Плавающий мусор","Қалқымалы қоқыс","Floating waste")}</option><option>{loc(language,"Возможный сброс","Ықтимал төгінді","Possible discharge")}</option><option>{loc(language,"Неприятный запах","Жағымсыз иіс","Odor")}</option><option>{loc(language,"Изменение цвета воды","Су түсінің өзгеруі","Water color change")}</option><option>{loc(language,"Мёртвая рыба","Өлі балық","Dead fish")}</option></select></label><label>{t(language,"reports.date")}<input name="date" type="datetime-local" required/></label><label className="wide">{t(language,"reports.description")}<textarea name="description" required/></label><label>{t(language,"reports.location")}<input name="location" placeholder={loc(language,"Астана, набережная Есиля","Астана, Есіл жағалауы","Astana, Esil embankment")} required/></label><label className="wide">{t(language,"reports.photo")}<input type="file" accept="image/*" aria-describedby="photo-note"/><small id="photo-note">{t(language,"reports.photoNote")}</small></label>{error&&<p className="rp-error wide">{error}</p>}<button className="rp-button primary wide" type="submit"><Send size={17}/>{t(language,"reports.submit")}</button></form>}</section><AlertFeed language={language}/></div></main>
}
function AlertFeed({language,compact=false}:{language:Language;compact?:boolean}){const alerts=language==="RU"?[["14:32","Есиль · Центральный парк","Маршрут очистки завершён"],["13:48","Есиль · мост Атырау","Рост мутности требует проверки"],["12:10","Нура · контрольный створ","Станция не передаёт данные"]]:language==="KZ"?[["14:32","Есіл · Орталық саябақ","Тазалау бағыты аяқталды"],["13:48","Есіл · Атырау көпірі","Лайлылықтың өсуін тексеру қажет"],["12:10","Нұра · бақылау тұстамасы","Станция дерек жібермейді"]]:[["14:32","Esil · Central Park","Cleanup route completed"],["13:48","Esil · Atyrau Bridge","Turbidity rise needs review"],["12:10","Nura · Control Section","Station is not transmitting"]];return <aside className="rp-card rp-panel"><h2>{t(language,"admin.alertFeed")}</h2>{alerts.slice(0,compact?3:alerts.length).map((a,i)=><div className="rp-alert-row" key={a[0]}><i className={i===1?"warn":i===2?"offline":""}/><div><b>{a[2]}</b><span>{a[1]} · {a[0]}</span></div></div>)}</aside>}

function LearnPage({language}:{language:Language}){
  const cards=[["learn.one","learn.oneText",Globe2],["learn.two","learn.twoText",Trash2],["learn.three","learn.threeText",Database],["learn.four","learn.fourText",ShieldCheck]] as const;
  return <main className="rp-content"><PageTitle kicker="RiverPulse Learn" title={t(language,"learn.title")}/><div className="rp-learn-grid">{cards.map(([heading,body,Icon])=><article className="rp-card rp-lesson" key={heading}><Icon size={26}/><h2>{t(language,heading)}</h2><details><summary className="rp-button secondary">{t(language,"learn.read")}<ArrowRight size={16}/></summary><p>{t(language,body)}</p></details></article>)}</div></main>
}
function AboutPage({language}:{language:Language}){return <main className="rp-content"><section className="rp-about"><span className="rp-kicker">RiverPulse · 2026</span><h1>{t(language,"about.title")}</h1><p>{t(language,"about.text")}</p></section><div className="rp-step-grid"><Metric label={t(language,"analytics.stations")} value="6"/><Metric label={t(language,"analytics.online")} value="83%"/><Metric label={loc(language,"Подтверждено лабораторией","Зертхана растаған","Lab verified")} value="6"/><Metric label={t(language,"analytics.operations")} value="14"/></div></main>}

function LoginPage({language}:{language:Language}){
  const register=typeof window!=="undefined"&&window.location.pathname==="/register";
  const [role,setRole]=useState<"user"|"admin">("user");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  async function submit(e:React.FormEvent){
    e.preventDefault();setLoading(true);setError("");
    const admin=role==="admin"&&!register;
    try{
      const response=await fetch(admin?"/api/admin-login":"/api/user-auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(admin?{password}:{action:register?"register":"login",email,password})});
      const result=await response.json() as {ok?:boolean;token?:string;error?:string};
      if(response.ok&&result.token){sessionStorage.setItem(admin?"riverpulse-admin-session":"riverpulse-user-session",result.token);window.location.assign(admin?"/operator":"/dashboard");return}
      setError(response.status===503?t(language,admin?"login.unconfigured":"login.unavailable"):admin?t(language,"login.error"):result.error==="exists"?t(language,"login.exists"):result.error==="invalid_input"?t(language,"login.invalid"):t(language,"login.userError"));
    }catch{setError(t(language,"login.unavailable"))}finally{setLoading(false)}
  }
  return <main className="rp-auth"><form className="rp-card rp-auth-card" onSubmit={submit}><Brand/><h1>{t(language,register?"login.registerTitle":"login.title")}</h1><DemoNotice language={language}/>{!register&&<label>{t(language,"login.account")}<select value={role} onChange={e=>setRole(e.target.value as "user"|"admin")}><option value="user">{t(language,"login.user")}</option><option value="admin">{t(language,"login.admin")}</option></select></label>}{(role==="user"||register)&&<label>{t(language,"login.email")}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="name@example.com" autoComplete="email"/></label>}<label>{t(language,role==="admin"&&!register?"login.password":"login.userPassword")}<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={role==="admin"&&!register?undefined:8} autoComplete={register?"new-password":"current-password"}/></label>{error&&<p className="rp-error" role="alert">{error}</p>}<button className="rp-button primary full" disabled={loading}>{loading?<RefreshCw className="spin" size={17}/>:null}{t(language,register?"login.register":"login.submit")}</button><a className="rp-auth-link" href={register?"/login":"/register"}>{t(language,register?"login.haveAccount":"login.needAccount")}</a></form></main>
}
function UserGate({language}:{language:Language}){const [email,setEmail]=useState<string|null>(null);const [loading,setLoading]=useState(true);useEffect(()=>{const token=sessionStorage.getItem("riverpulse-user-session");fetch("/api/user-auth",{headers:token?{authorization:"Bearer "+token}:{},cache:"no-store"}).then(async response=>{if(response.ok){const data=await response.json() as {email:string};setEmail(data.email)}}).catch(()=>{}).finally(()=>setLoading(false))},[]);if(loading)return <Loading/>;if(!email)return <LoginPage language={language}/>;return <UserDashboard language={language} email={email}/>}
function UserDashboard({language,email}:{language:Language;email:string}){return <main className="rp-content"><PageTitle kicker={email} title={loc(language,"Личный кабинет","Жеке кабинет","Personal dashboard")} subtitle={t(language,"common.updated")} action={<button className="rp-button secondary" onClick={()=>{sessionStorage.removeItem("riverpulse-user-session");window.location.assign("/login")}}><LogOut size={16}/>{t(language,"admin.logout")}</button>}/><div className="rp-two-grid"><section className="rp-card rp-panel"><h2>{t(language,"nav.water")}</h2>{waterStations.slice(0,3).map(s=><a href={"/water/"+s.id} className="rp-saved-row" key={s.id}><div><b>{s.waterBody[language]}</b><span>{s.name[language]}</span></div><Badge status={s.status} language={language}/></a>)}</section><AlertFeed language={language}/></div></main>}

function AdminGate({language}:{language:Language}){const [state,setState]=useState<"loading"|"ok"|"denied">("loading");useEffect(()=>{const token=sessionStorage.getItem("riverpulse-admin-session");fetch("/api/admin-session",{cache:"no-store",headers:token?{authorization:"Bearer "+token}:{}}).then(r=>setState(r.ok?"ok":"denied")).catch(()=>setState("denied"))},[]);if(state==="loading")return <Loading/>;if(state==="denied")return <LoginPage language={language}/>;return <AdminDashboard language={language}/>}
function AdminDashboard({language}:{language:Language}){
  const [reports,setReports]=useState<DemoReport[]>([]);
  useEffect(()=>{try{setReports(JSON.parse(localStorage.getItem(demoReportsKey)||"[]") as DemoReport[])}catch{setReports([])}},[]);
  async function logout(){sessionStorage.removeItem("riverpulse-admin-session");await fetch("/api/admin-session",{method:"DELETE"});window.location.assign("/login")}
  const rivers=language==="RU"?[["Есиль","Астана","74","2","4 / 4"],["Нура","Акмолинская область","63","0","0 / 1"],["Коргалжынские озёра","Коргалжынский район","81","0","1 / 1"]]:language==="KZ"?[["Есіл","Астана","74","2","4 / 4"],["Нұра","Ақмола облысы","63","0","0 / 1"],["Қорғалжын көлдері","Қорғалжын ауданы","81","0","1 / 1"]]:[["Esil","Astana","74","2","4 / 4"],["Nura","Akmola Region","63","0","0 / 1"],["Korgalzhyn Lakes","Korgalzhyn District","81","0","1 / 1"]];
  const adminEvents=language==="RU"?[["14:32","Есиль · Центральный парк","Маршрут очистки завершён","RiverCleaner RC-01","А. Сарсенов","Закрыто"],["13:48","Есиль · мост Атырау","Мутность +38%","Датчик + AI","Д. Омарова","Проверка"],["12:10","Нура · контрольный створ","Станция отключена","Система","М. Аскаров","Открыто"],["10:24","Озеро Коргалжын","Получен лабораторный анализ","Лаборатория","А. Сарсенов","Подтверждено"]]:language==="KZ"?[["14:32","Есіл · Орталық саябақ","Тазалау бағыты аяқталды","RiverCleaner RC-01","А. Сәрсенов","Жабық"],["13:48","Есіл · Атырау көпірі","Лайлылық +38%","Датчик + AI","Д. Омарова","Тексеру"],["12:10","Нұра · бақылау тұстамасы","Станция өшірулі","Жүйе","М. Асқаров","Ашық"],["10:24","Қорғалжын көлі","Зертханалық талдау алынды","Зертхана","А. Сәрсенов","Расталды"]]:[["14:32","Esil · Central Park","Cleanup route completed","RiverCleaner RC-01","A. Sarsenov","Closed"],["13:48","Esil · Atyrau Bridge","Turbidity +38%","Sensor + AI","D. Omarova","Review"],["12:10","Nura · Control Section","Station offline","System","M. Askarov","Open"],["10:24","Korgalzhyn Lake","Lab result received","Laboratory","A. Sarsenov","Verified"]];
  return <main className="rp-admin"><PageTitle kicker={t(language,"login.admin")} title={t(language,"admin.title")} subtitle={t(language,"admin.subtitle")} action={<button className="rp-button secondary" onClick={logout}><LogOut size={16}/>{t(language,"admin.logout")}</button>}/><DemoNotice language={language}/><div className="rp-admin-metrics"><Metric label={t(language,"analytics.stations")} value="6" meta={loc(language,"5 онлайн","5 онлайн","5 online")}/><Metric label={t(language,"analytics.alerts")} value="3" meta={loc(language,"1 высокий риск","1 жоғары қауіп","1 high risk")}/><Metric label={t(language,"analytics.response")} value={loc(language,"42 мин","42 мин","42 min")}/><Metric label={t(language,"analytics.collected")} value="186 kg"/></div><div className="rp-admin-grid"><section className="rp-card rp-panel rp-admin-map"><h2>{t(language,"admin.rivers")}</h2><RealWaterMap language={language} selectedId="esil-central" onSelect={noop}/></section><AlertFeed language={language}/></div><section className="rp-card rp-panel"><h2>{t(language,"admin.rivers")}</h2><div className="rp-table-wrap"><table><thead><tr><th>{t(language,"nav.water")}</th><th>{t(language,"admin.place")}</th><th>{loc(language,"Состояние воды","Судың күйі","Water Condition")}</th><th>{t(language,"analytics.alerts")}</th><th>{t(language,"analytics.online")}</th><th>{loc(language,"Статус","Күй","Status")}</th></tr></thead><tbody>{rivers.map((r,i)=><tr key={r[0]}>{r.slice(0,5).map(c=><td key={c}>{c}</td>)}<td><Badge status={i===0?"risk":i===1?"offline":"normal"} language={language}/></td></tr>)}</tbody></table></div></section><section className="rp-card rp-panel"><h2>{t(language,"admin.alertFeed")}</h2><div className="rp-table-wrap"><table><thead><tr><th>{t(language,"admin.time")}</th><th>{t(language,"admin.place")}</th><th>{t(language,"admin.event")}</th><th>{t(language,"admin.source")}</th><th>{t(language,"admin.owner")}</th><th>{loc(language,"Статус","Күй","Status")}</th></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td>{r.date.replace("T"," ")}</td><td>{r.location}</td><td>{r.category}: {r.description}</td><td>{t(language,"reports.localOnly")}</td><td>—</td><td>{r.id}</td></tr>)}{adminEvents.map(r=><tr key={r[0]}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></div></section></main>
}

function Footer({language}:{language:Language}){return <footer className="rp-footer"><div className="shell"><Brand/><span>© 2026 · {t(language,"common.demo")}</span></div></footer>}
function Loading(){return <div className="rp-loading"><RefreshCw className="spin"/><span>RiverPulse</span></div>}
function AppRouter({language}:{language:Language}){const path=typeof window!=="undefined"?window.location.pathname:"/";if(path==="/")return <Home language={language}/>;if(path==="/map")return <MapPage language={language}/>;if(path.startsWith("/water/"))return <WaterPage key={path} language={language} station={waterStations.find(s=>s.id===decodeURIComponent(path.split("/")[2]))||waterStations[0]}/>;if(path.startsWith("/robots/"))return <RobotPage language={language}/>;if(path==="/analytics")return <AnalyticsPage language={language}/>;if(path==="/reports")return <ReportsPage language={language}/>;if(path==="/learn")return <LearnPage language={language}/>;if(path==="/about")return <AboutPage language={language}/>;if(path==="/login"||path==="/register")return <LoginPage language={language}/>;if(path==="/operator")return <AdminGate language={language}/>;if(path==="/dashboard")return <UserGate language={language}/>;return <Home language={language}/>}

export default function RiverPulseApp(){
  const [language,setLanguage]=useState<Language>("RU");const [theme,setTheme]=useState("dark");const [ready,setReady]=useState(false);
  useEffect(()=>{const lang=(localStorage.getItem("riverpulse-language")||"RU") as Language;const savedTheme=localStorage.getItem("riverpulse-theme")||"dark";setLanguage(lang);setTheme(savedTheme);document.documentElement.classList.toggle("dark",savedTheme==="dark");setReady(true)},[]);
  useEffect(()=>{if(!ready)return;localStorage.setItem("riverpulse-language",language);document.documentElement.lang=language==="RU"?"ru":language==="KZ"?"kk":"en"},[language,ready]);
  useEffect(()=>{if(!ready)return;localStorage.setItem("riverpulse-theme",theme);document.documentElement.classList.toggle("dark",theme==="dark")},[theme,ready]);
  if(!ready)return <Loading/>;
  return <><Header language={language} setLanguage={setLanguage} theme={theme} setTheme={setTheme}/><AppRouter language={language}/></>
}
